### ISSUE TITLE
Script is no longer working

### ISSUE THREAD

**Issue by bckelley** [kimjisena/vscode-server#1]
seems microsoft has deleted things and this doesn't work any longer

**Comment by kimjisena** [comment]
> seems microsoft has deleted things and this doesn't work any longer

Can you elaborate more on the issue you're facing? Perhaps error messages and/or stack traces. Would be happy to assist.

**Comment by bckelley** [comment]
Running the script:
`glibc version is 2.36
is min? 1
Installing from https://aka.ms/vscode-server-launcher/aarch64-unknown-linux-gnu`

Running `code-server`
`code-server
/usr/local/bin/code-server: line 1: syntax error near unexpected token `newline'
/usr/local/bin/code-server: line 1: `<!DOCTYPE html>'`

After clicking on the Aka.ms it opens this page for vscode-remote-tunnel `https://code.visualstudio.com/docs/remote/tunnels`

**Comment by kimjisena** [comment]
Well @bckelley, you closed the issue. Did you figure it out? Mind sharing what solved it for you?
